database:
  server_url: postgres://postgres:notsecurepassword@localhost:5432/zksync_server_localhost_zkchain
  prover_url: postgres://postgres:notsecurepassword@localhost/prover_local
l1:
  l1_rpc_url: http://127.0.0.1:8545
consensus:
  validator_key: validator:secret:bls12_381:43d19f30b373aeab4b45c6a412f65afb31275fa2dc676454eb5bca2823321efc
  node_key: node:secret:ed25519:65f05a900b9753d10d5e0e42dac082689adf71bb79c2dbd6dfcded4f46c84947
