database:
  server_url: postgres://postgres:notsecurepassword@localhost:5432/zksync_server_localhost_custom_zk_chain
  prover_url: postgres://postgres:notsecurepassword@localhost/prover_local
l1:
  l1_rpc_url: http://127.0.0.1:8545
consensus:
  validator_key: validator:secret:bls12_381:2c14c1e94122644d8191668dd87c5907910e6664af68748daaa70eddfe9efe0f
  node_key: node:secret:ed25519:b10b28c2dac079aaaa61584925502c3183a4ea384ff930fe164a466d1187ba44
